#-----------
# SENSORS
#-----------
sensor:
  ##
  # Diagnostics wifi and uptime
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: clack_wifi_signal_db
    name: ${name} WiFi Signal dB
    update_interval: 60s
    device_class: signal_strength
    entity_category: diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: clack_wifi_signal_db
    id: clack_wifi_signal_db_percent
    name: ${name} WiFi Signal
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

  - platform: uptime
    id: clack_uptime
    name: ${name} ${clack_uptime}
    unit_of_measurement: ${days}
    update_interval: 3600s
    accuracy_decimals: 1
    filters:
      - multiply: 0.000011574