substitutions:
  # General substitutions:
  name: clack
  device_description: "Esphome component for Clack WS1 softener with TOF sensor saltlevel detection"
  timezone: "Europe/Amsterdam"
  # Interval substitutions:
  salt_level_update_interval: 30s
  watermeter_update_interval: 600s # 10 minutes
  tank_percentage_update_interval: 600s
  clack_height_update_interval: 600s
  pulse_liters: "2.15"

# In order to use other language fix clack-label filename below:
# Currently supported languages are en (english), nl (dutch).
# ESP32-wemos-s3 is a wemos lolin S3 mini
packages:
  remote_package:
    url: https://github.com/fonske/clack-reader-v3
    ref: main
    refresh: 0s
    files: [ 
      esphome/.clack-base.yaml, 
      esphome/.clack-optional.yaml,
      esphome/.clack-labels-en.yaml, 
      esphome/board-esp32-wemos-s3.yaml
    ]

## for developing/testing, uncomment local includes and comment out above remote_package packages part.
#packages:
#  substitutions: !include .clack-labels-en.yaml
#  substitutions: !include .clack-labels-nl.yaml
#  device_base1:  !include board-esp32-wemos-s3.yaml

time:
  - platform: sntp
    id: clack_sntp_time
    timezone: ${timezone}
    # Enable this with your own NTP server if your device is on a no internet IOT lan. 
    #servers: 192.168.X.X

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: "configesp"
    ap_timeout: 15s
